version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: smartdoc_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=devpass
      - POSTGRES_DB=smartdoc
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: